unique_ids:
  assets:
    standard-page.html: EV7PUOALGDZ3XFGWTWPD32DJSNCJ5JHC
    theme.css: AQ4VZGWXHQIKDWX536F42RUQWFYRUKXP
  forms:
    AccountComponent: NH52OYX2Y2V5ANRBAPGYZ5GIDQQTTBMP
    AddMeasurementComponent: 4GXO2Q674BWTTYSBTLJEJYHY7NYDVVOD
    CompareComponent: 3QZRKXFISZYWNOQJZBOICXQTKIP3E6IF
    HomeAnonComponent: AYAIFBD44DNCRAXU7ADMNZXA47VROE55
    HomeDetailsComponent: 3VYVZN2F4O4MJ35YZGRSD4OXWZ4SWXR5
    HomeForm: I37VIHIF3AQJZJ2A4PZ6TVQRFQRB5GWB
    SetHeightComponent: PM3EGH6BL5EPMLJNIG5H7CE3IGB5VNQN
  modules:
    data_access: 7DQ4OIBH57LZJ5BZANYSG2FLSN7BVEQ7
    navigation: 4CKPAIKFGKLXPWJSKRNPZIE2VPDARMIG
  scripts: {}
  server_modules:
    api: GWFXXBWQV7LNXH4MYZK74AEGCA3BO7KF
    auth: 4JLAEMTXBDBVMVORGYXJCPFTC3ZIX777
    data_loader: MRBBMSJRS64BRWH5MUH4JBDHSTKTWPGI
    measurement_service: J3MZJVLZLO5NAHREMCQNMFWP5TH5LKVC
